#!/usr/bin/env python
# coding: utf-8

# In[14]:


###这里是模块
import turtle


###这里是程序主体
turtle.speed(0) # 速度
turtle.getscreen().bgcolor("purple")
# 左手
turtle.penup()
turtle.goto(89, 56)
turtle.pencolor("lightgray")
turtle.pensize(2)
turtle.fillcolor("white")
turtle.begin_fill()
turtle.pendown()
turtle.setheading(80)
turtle.circle(-23, 200)
turtle.circle(-150, 23)
turtle.end_fill()
# 左手内
turtle.penup()
turtle.goto(91, 48)
turtle.pencolor("black")
turtle.pensize(1)
turtle.fillcolor("black")
turtle.begin_fill()
turtle.setheading(95)
turtle.pendown()
turtle.circle(-19, 160)
turtle.circle(-10, 50)
turtle.circle(-100, 30)
turtle.end_fill()
# 轮廓
# 头顶
turtle.penup()
turtle.goto(-37, 115)
turtle.pencolor("lightgray")
turtle.pensize(2)
turtle.fillcolor("white")
turtle.begin_fill()
turtle.pendown()
turtle.setheading(20)
turtle.circle(-125, 35)
# 左耳
turtle.setheading(50)
turtle.circle(-21, 180)
# 左侧
turtle.setheading(-50)
turtle.circle(-95, 30)
turtle.circle(-160, 45)
# 左腿
turtle.circle(60, 30)
turtle.circle(100, 12)
turtle.circle(-9, 85)
turtle.circle(-90, 23)
turtle.circle(-10, 110)
turtle.circle(8, 115)
turtle.circle(50, 12)
# 右腿
turtle.circle(8, 120)
turtle.circle(-8, 110)
turtle.circle(-75, 30)
turtle.circle(-8, 70)
turtle.circle(-75, 10)
turtle.circle(100, 35)
turtle.circle(-75, 20)
# 右手
turtle.setheading(-120)
turtle.circle(25, 30)
turtle.circle(-18, 200)
turtle.circle(-150, 23)
# 右侧
turtle.setheading(86)
turtle.circle(-150, 26)
# 右耳
turtle.setheading(122)
turtle.circle(-27, 160)
turtle.end_fill()
# 右耳内
turtle.penup()
turtle.goto(-65, 90)
turtle.pencolor("black")
turtle.pensize(1)
turtle.fillcolor("black")
turtle.begin_fill()
turtle.pendown()
turtle.setheading(120)
turtle.circle(-14, 160)
turtle.setheading(210)
turtle.circle(75, 20)
turtle.end_fill()
# 左耳内
turtle.penup()
turtle.goto(45, 115)
turtle.setheading(40)
turtle.begin_fill()
turtle.pendown()
turtle.circle(-15, 170)
turtle.setheading(125)
turtle.circle(75, 23)
turtle.end_fill()
# 右手内
turtle.penup()
turtle.goto(-90, -28)
turtle.fillcolor("black")
turtle.begin_fill()
turtle.setheading(-120)
turtle.pendown()
turtle.circle(25, 30)
turtle.circle(-14, 200)
turtle.circle(-150, 20)
turtle.setheading(-90)
turtle.circle(150, 14)
turtle.end_fill()
# 左腿内
turtle.penup()
turtle.goto(54, -84)
turtle.fillcolor("black")
turtle.begin_fill()
turtle.pendown()
turtle.setheading(-115)
turtle.circle(55, 15)
turtle.circle(100, 10)
turtle.circle(-9, 80)
turtle.circle(-90, 13)
turtle.circle(-10, 90)
turtle.circle(8, 60)
turtle.setheading(42)
turtle.circle(-100, 29)
turtle.end_fill()
# 右腿内
turtle.penup()
turtle.goto(-19, -105)
turtle.fillcolor("black")
turtle.begin_fill()
turtle.pendown()
turtle.setheading(-155)
turtle.circle(8, 100)
turtle.circle(-5, 110)
turtle.circle(-50, 30)
turtle.circle(-8, 65)
turtle.circle(-50, 10)
turtle.circle(100, 15)
turtle.setheading(-14)
turtle.circle(-100, 27)
turtle.end_fill()
# 右眼
# 眼圈
turtle.penup()
turtle.goto(-32, 60)
turtle.begin_fill()
turtle.pendown()
turtle.setheading(40)
turtle.circle(-18, 152)
turtle.circle(-50, 50)
turtle.circle(-18, 130)
turtle.circle(-50, 50)
turtle.end_fill()
# 眼珠
turtle.penup()
turtle.goto(-24, 28)
turtle.fillcolor("white")
turtle.begin_fill()
turtle.pendown()
turtle.setheading(0)
turtle.circle(13, 360)
turtle.end_fill()
turtle.penup()
turtle.goto(-23, 31)
turtle.pencolor("darkslategray")
turtle.fillcolor("darkslategray")
turtle.begin_fill()
turtle.pendown()
turtle.setheading(0)
turtle.circle(10, 360)
turtle.end_fill()
turtle.penup()
turtle.goto(-23, 34)
turtle.fillcolor("black")
turtle.begin_fill()
turtle.pendown()
turtle.setheading(0)
turtle.circle(5, 360)
turtle.end_fill()
turtle.penup()
turtle.goto(-24, 43)
turtle.pencolor("white")
turtle.fillcolor("white")
turtle.begin_fill()
turtle.pendown()
turtle.setheading(0)
turtle.circle(3, 360)
turtle.end_fill()
# 左眼
# 眼圈
turtle.penup()
turtle.goto(26, 41)
turtle.fillcolor("black")
turtle.begin_fill()
turtle.pendown()
turtle.setheading(120)
turtle.circle(-16, 152)
turtle.circle(-50, 55)
turtle.circle(-13, 120)
turtle.circle(-60, 45)
turtle.end_fill()
# 眼珠
turtle.penup()
turtle.goto(40, 30)
turtle.fillcolor("white")
turtle.begin_fill()
turtle.pendown()
turtle.setheading(0)
turtle.circle(12, 360)
turtle.end_fill()
turtle.penup()
turtle.goto(40, 32)
turtle.pencolor("darkslategray")
turtle.fillcolor("darkslategray")
turtle.begin_fill()
turtle.pendown()
turtle.setheading(0)
turtle.circle(10, 360)
turtle.end_fill()
turtle.penup()
turtle.goto(40, 35)
turtle.fillcolor("black")
turtle.begin_fill()
turtle.pendown()
turtle.setheading(0)
turtle.circle(5, 360)
turtle.end_fill()
turtle.penup()
turtle.goto(40, 44)
turtle.pencolor("white")
turtle.fillcolor("white")
turtle.begin_fill()
turtle.pendown()
turtle.setheading(0)
turtle.circle(3, 360)
turtle.end_fill()
# 鼻子
turtle.penup()
turtle.goto(19, 40)
turtle.fillcolor("black")
turtle.begin_fill()
turtle.pendown()
turtle.circle(-4, 130)
turtle.circle(-11, 100)
turtle.circle(-4, 130)
turtle.end_fill()
# 嘴
turtle.penup()
turtle.goto(-8, 24)
turtle.setheading(-36)
turtle.begin_fill()
turtle.pendown()
turtle.circle(30, 70)
turtle.setheading(-132)
turtle.circle(-23, 100)
turtle.end_fill()
# 彩虹圈
turtle.penup()
turtle.goto(-68, 60)
turtle.pensize(3)
turtle.pencolor("cyan")
turtle.pendown()
turtle.setheading(60)
turtle.circle(-83, 150)
turtle.circle(-65, 78)
turtle.circle(-125, 30)
turtle.circle(-69, 105)
turtle.penup()
turtle.goto(-66, 58)
turtle.pencolor("slateblue")
turtle.pendown()
turtle.setheading(60)
turtle.circle(-80, 144)
turtle.circle(-60, 78)
turtle.circle(-121, 30)
turtle.circle(-68, 105)
turtle.penup()
turtle.goto(-64, 56)
turtle.pencolor("orangered")
turtle.pendown()
turtle.setheading(60)
turtle.circle(-78, 136)
turtle.circle(-58, 86)
turtle.circle(-110, 30)
turtle.circle(-67, 103)
turtle.penup()
turtle.goto(-62, 54)
turtle.pencolor("gold")
turtle.pendown()
turtle.setheading(60)
turtle.circle(-75, 136)
turtle.circle(-52, 86)
turtle.circle(-110, 30)
turtle.circle(-63, 102)
turtle.penup()
turtle.goto(-60, 52)
turtle.pencolor("greenyellow")
turtle.pendown()
turtle.setheading(60)
turtle.circle(-73, 136)
turtle.circle(-45, 83)
turtle.circle(-110, 30)
turtle.circle(-60, 100)
turtle.penup()
# 爱心
turtle.penup()
turtle.goto(110, 58)
turtle.pencolor("brown")
turtle.pensize(1)
turtle.fillcolor("brown")
turtle.begin_fill()
turtle.pendown()
turtle.setheading(36)
turtle.circle(-4, 180)
turtle.circle(-30, 24)
turtle.setheading(110)
turtle.circle(-30, 24)
turtle.circle(-4, 180)
turtle.end_fill()
# 五环
turtle.penup()
turtle.goto(-3, -85)
turtle.pendown()
turtle.pencolor("blue")
turtle.circle(3)
turtle.penup()
turtle.goto(5, -85)
turtle.pendown()
turtle.pencolor("black")
turtle.circle(3)
turtle.penup()
turtle.goto(13, -85)
turtle.pendown()
turtle.pencolor("brown")
turtle.circle(3)
turtle.penup()
turtle.goto(1, -88)
turtle.pendown()
turtle.pencolor("lightgoldenrod")
turtle.circle(3)
turtle.penup()
turtle.goto(8, -88)
turtle.pendown()
turtle.pencolor("green")
turtle.circle(3)
turtle.penup()
turtle.pencolor("black")
turtle.goto(-8, -80)
turtle.write("BEIJING 2022", font=('Arial', 8, 'bold italic'))
turtle.hideturtle()
turtle.done()


###运行后输出

